; Listing generated by Microsoft (R) Optimizing Compiler Version 13.10.3077 

	TITLE	.\main.cpp
	.386P
include listing.inc
if @Version gt 510
.model FLAT
else
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
_BSS	SEGMENT DWORD USE32 PUBLIC 'BSS'
_BSS	ENDS
$$SYMBOLS	SEGMENT BYTE USE32 'DEBSYM'
$$SYMBOLS	ENDS
$$TYPES	SEGMENT BYTE USE32 'DEBTYP'
$$TYPES	ENDS
_TLS	SEGMENT DWORD USE32 PUBLIC 'TLS'
_TLS	ENDS
;	COMDAT ??_C@_0O@JNMCMGBH@?2?2?4?2HelloDDKB?$AA@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT ??_C@_0EC@FLCPNAEB@Failed?5to?5obtain?5file?5handle?5to?5@
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
;	COMDAT _IsEqualGUID
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT _==
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
;	COMDAT _main
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
sxdata	SEGMENT DWORD USE32 'SXDATA'
sxdata	ENDS
FLAT	GROUP _DATA, CONST, _BSS
	ASSUME	CS: FLAT, DS: FLAT, SS: FLAT
endif

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

PUBLIC	_main
PUBLIC	??_C@_0O@JNMCMGBH@?2?2?4?2HelloDDKB?$AA@	; `string'
PUBLIC	??_C@_0EC@FLCPNAEB@Failed?5to?5obtain?5file?5handle?5to?5@ ; `string'
EXTRN	__imp__printf:NEAR
EXTRN	__RTC_InitBase:NEAR
EXTRN	__RTC_Shutdown:NEAR
EXTRN	__RTC_CheckEsp:NEAR
EXTRN	@_RTC_CheckStackVars@8:NEAR
EXTRN	__imp__GetLastError@0:NEAR
EXTRN	__imp__ReadFile@20:NEAR
EXTRN	__imp__CloseHandle@4:NEAR
EXTRN	__imp__CreateFileA@28:NEAR
;	COMDAT rtc$IMZ
; File d:\tmp\windows驱动开发技术详解_v2_qzj\chapter11\test8\test\main.cpp
rtc$IMZ	SEGMENT
__RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase
rtc$IMZ	ENDS
;	COMDAT rtc$TMZ
rtc$TMZ	SEGMENT
__RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT ??_C@_0O@JNMCMGBH@?2?2?4?2HelloDDKB?$AA@
CONST	SEGMENT
??_C@_0O@JNMCMGBH@?2?2?4?2HelloDDKB?$AA@ DB '\\.\HelloDDKB', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0EC@FLCPNAEB@Failed?5to?5obtain?5file?5handle?5to?5@
CONST	SEGMENT
??_C@_0EC@FLCPNAEB@Failed?5to?5obtain?5file?5handle?5to?5@ DB 'Failed to '
	DB	'obtain file handle to device with Win32 error code: %d', 0aH, 00H ; `string'
; Function compile flags: /Odt /RTCs /ZI
CONST	ENDS
;	COMDAT _main
_TEXT	SEGMENT
_dRet$ = -20						; size = 4
_hDevice$ = -8						; size = 4
_main	PROC NEAR					; COMDAT
; Line 5
	push	ebp
	mov	ebp, esp
	sub	esp, 216				; 000000d8H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-216]
	mov	ecx, 54					; 00000036H
	mov	eax, -858993460				; ccccccccH
	rep stosd
; Line 14
	mov	esi, esp
	push	0
	push	128					; 00000080H
	push	3
	push	0
	push	0
	push	-1073741824				; c0000000H
	push	OFFSET FLAT:??_C@_0O@JNMCMGBH@?2?2?4?2HelloDDKB?$AA@
	call	DWORD PTR __imp__CreateFileA@28
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _hDevice$[ebp], eax
; Line 16
	cmp	DWORD PTR _hDevice$[ebp], -1
	jne	SHORT $L55551
; Line 20
	mov	esi, esp
	call	DWORD PTR __imp__GetLastError@0
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	esi, esp
	push	eax
	push	OFFSET FLAT:??_C@_0EC@FLCPNAEB@Failed?5to?5obtain?5file?5handle?5to?5@
	call	DWORD PTR __imp__printf
	add	esp, 8
	cmp	esi, esp
	call	__RTC_CheckEsp
; Line 21
	mov	eax, 1
	jmp	SHORT $L55546
$L55551:
; Line 25
	mov	esi, esp
	push	0
	lea	eax, DWORD PTR _dRet$[ebp]
	push	eax
	push	0
	push	0
	mov	ecx, DWORD PTR _hDevice$[ebp]
	push	ecx
	call	DWORD PTR __imp__ReadFile@20
	cmp	esi, esp
	call	__RTC_CheckEsp
; Line 27
	mov	esi, esp
	mov	eax, DWORD PTR _hDevice$[ebp]
	push	eax
	call	DWORD PTR __imp__CloseHandle@4
	cmp	esi, esp
	call	__RTC_CheckEsp
; Line 29
	xor	eax, eax
$L55546:
; Line 30
	push	edx
	mov	ecx, ebp
	push	eax
	lea	edx, DWORD PTR $L55581
	call	@_RTC_CheckStackVars@8
	pop	eax
	pop	edx
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 216				; 000000d8H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
$L55581:
	DD	1
	DD	$L55580
$L55580:
	DD	-20					; ffffffecH
	DD	4
	DD	$L55579
$L55579:
	DB	100					; 00000064H
	DB	82					; 00000052H
	DB	101					; 00000065H
	DB	116					; 00000074H
	DB	0
_main	ENDP
_TEXT	ENDS
END
