# =========================================================================
#     This makefile was generated by
#     Bakefile 0.2.9 (http://www.bakefile.org)
#     Do not modify, all changes will be overwritten!
# =========================================================================



# -------------------------------------------------------------------------
# These are configurable options:
# -------------------------------------------------------------------------

# C++ compiler 
CXX = cl

# Standard flags for C++ 
CXXFLAGS = 

# Standard preprocessor flags (common for CC and CXX) 
CPPFLAGS = 

# Standard linker flags 
LDFLAGS = 



# -------------------------------------------------------------------------
# Do not modify the rest of this file!
# -------------------------------------------------------------------------

### Variables: ###

CONSOLETEST_CXXFLAGS = /MD /DWIN32 /GR /EHsc /nologo /W3 /Gm /GX /ZI /Od /D "WIN32" /D \
	"_DEBUG" /D "_CONSOLE" /D "_MBCS" /YX /FD /GZ /c /nologo /W3 /Gm /GR /GX /ZI /Od /D \
	"WIN32" /D "_DEBUG" /D "_CONSOLE" /D "_MBCS" /FA /YX /FD /GZ /c $(CPPFLAGS) \
	$(CXXFLAGS)
CONSOLETEST_OBJECTS =  \
	ConsoleTest_main.obj

### Conditionally set variables: ###



### Targets: ###

all: ConsoleTest.exe

clean: 
	-if exist .\*.obj del .\*.obj
	-if exist .\*.res del .\*.res
	-if exist .\*.pch del .\*.pch
	-if exist ConsoleTest.exe del ConsoleTest.exe
	-if exist ConsoleTest.ilk del ConsoleTest.ilk
	-if exist ConsoleTest.pdb del ConsoleTest.pdb

ConsoleTest.exe: $(CONSOLETEST_OBJECTS)
	link /NOLOGO /OUT:$@  /nologo /stack:0x300000 /subsystem:console /map /debug /machine:I386 /pdbtype:sept $(LDFLAGS) @<<
	$(CONSOLETEST_OBJECTS)   Strmiids.lib ole32.lib User32.lib setupapi.lib Advapi32.lib
<<

ConsoleTest_main.obj: .\main.cpp
	$(CXX) /c /nologo /TP /Fo$@ $(CONSOLETEST_CXXFLAGS) .\main.cpp

